/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "NVIC_EXTI.h"
#include "SysCfg.h"
#include "RCC.h"
#include "GPIO.h"
#include "Timer.h"
#include "SPI.h"
#include "BLE.h"
#include "hci.h"
#include "LPS22HH.h"
#include "LSM6DSR.h"



/****************************************************************************
GLOBAL VARIABLES
****************************************************************************/
extern volatile uint32_t SysTick_Counter;


extern uint8_t set_connectable;
extern int connected;


/* Define FPU base address */
#define FPU_BASE_ADDRESS      (0xE000ED00UL)

/* FPU CPACR - Coprocessor access control register offset */
#define FPU_CPACR_OFFSET        (0x88UL)
/* FPU CPACR Register address */
#define FPU_CPACR_ADDRESS       (FPU_BASE_ADDRESS + FPU_CPACR_OFFSET)
#define FPU_CPACR               (* (volatile uint32_t *)(FPU_CPACR_ADDRESS)) // typecast and dereference
/* FPU CPACR CP10 offset */
#define FPU_CPACR2_CP10_OFFSET  (20UL) // 2 bits
/* FPU CPACR CP11 offset */
#define FPU_CPACR2_CP11_OFFSET  (22UL) // 2 bits


static inline void Enable_FPU(void)
{
	FPU_CPACR |= (3UL << FPU_CPACR2_CP10_OFFSET); // FPU Full Access
	FPU_CPACR |= (3UL << FPU_CPACR2_CP11_OFFSET); // FPU Full Access
}



int main(void)
{
	uint8_t retVal;
	static uint32_t SysTick_Last    = 0;
	static uint32_t SysTick_Last10ms = 0;

	/* Initialize Reset and Clock as well as Flash Memory Interface, required for PLL */
	RCC_Init();
	/* Initialize System Configuration Controller */
	SysCfg_Init();
	/* NVIC and EXTI initialization - Enable_Interrupts */
	NVIC_EXTI_Init();
	/* Enable Floating Point Unit */
	Enable_FPU(); // Required for usage of "float" data type operations

	__asm volatile ("cpsie i");

	/* Initialize General-Purpose Timer */
	Timer_Init();
	/* Initialize GPIOs */
	GPIO_Init();
	/* Initialize PWM-related registers */
	PWM_Init();
	/* Initialize SPI */
	SPI_Init();
	/* Initialize pressure sensor */
	LPS22HH_Pressure_Init();
	/* Initialize IMU sensor */
	LSM6DSR_Imu_Init();
	/* Initialize BLE */
	retVal = BLE_Init();
	(void)retVal;/* TODO Add countermeasure for error return */



	/****** TMP code for debugging purposes below to be removed ******/
	//volatile uint8_t who;

	//LSM6DSR_CS_LOW();
	//SPI2_FlushRX();
	//who = SPI2_Read(0x0F);
	//LSM6DSR_CS_HIGH();

	//LPS22HH_CS_LOW();
	//SPI2_FlushRX();
	//who = SPI2_Read(0x0F);
	//LPS22HH_CS_HIGH();
	/****** TMP code for debugging purposes above to be removed ******/
	

	/* Loop forever */
	while(1)
	{
		if(SysTick_Counter != SysTick_Last)
		{
				SysTick_Last = SysTick_Counter;
				LSM6DSR_Imu_Task(); // 1ms task


			if((SysTick_Counter - SysTick_Last10ms) >= 10) // Check if 10ms are elapsed
			{
				SysTick_Last10ms = SysTick_Counter;
				//////////////////////////* Processa BLE sia se c'è stato un IRQ, sia se il pin è già alto */
				/* Problem was happening for which BLE_IRQ_Counter was never incrementing, cause I was only checking for a rising edge of the IRQ pin, which was however already HIGH since the BLE boot */
				if (HCI_ProcessEvent) {
					HCI_ProcessEvent = 0;

					HCI_Process(); // empties the queue and calls HCI_Event_CB - 5ms task
				}
				if (set_connectable) {
					 //Now update the BLE advertize data and make the board connectable
					setConnectable();
					set_connectable = FALSE;
				}
			}

		}
	}

}
