/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "NVIC_EXTI.h"
#include "SysCfg.h"
#include "RCC.h"
#include "GPIO.h"
#include "Timer.h"
#include "SPI.h"
#include "LPS22HH.h"
#include "LIS2MDL.h"
#include "LSM6DSL.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/****************************************************************************
Global variables
****************************************************************************/
extern volatile uint32_t SysTick_Counter;




int main(void)
{
	static uint32_t SysTick_Last     = 0;
	static uint32_t SysTick_Last5ms  = 0;
	//float PWM_Mot1 = 0.0f;
	//float PWM_Mot2 = 0.0f;
	//float PWM_Mot3 = 0.0f;
	//float PWM_Mot4 = 0.0f;

	/* Initialize Reset and Clock as well as Flash Memory Interface, required for PLL */
	RCC_Init();
	/* NVIC and EXTI initialization - Enable_Interrupts */
	NVIC_EXTI_Init();
	/* Initialize System Configuration Controller */
	SysCfg_Init();
	/* Initialize General-Purpose Timer */
	Timer_Init();
	/* Initialize GPIOs */
	GPIO_Init();
	/* Initialize PWM-related registers */
	PWM_Init();
	/* Initialize SPI */
	SPI_Init();

	LPS22HH_Pressure_Init();

	LIS2MDL_Magnetom_Init();

	LSM6DSL_Imu_Init();




	/* Loop forever */
	while(1)
	{
		if(SysTick_Counter != SysTick_Last)
		{
			SysTick_Last = SysTick_Counter;
			LSM6DSL_Imu_Task();
			
			if((SysTick_Counter - SysTick_Last5ms) >= 5) // Check if 5ms are elapsed
			{
				SysTick_Last5ms = SysTick_Counter;
				//PWM_Set(PWM_Mot1, PWM_Mot2, PWM_Mot3, PWM_Mot4); // TODO: Re-enable with FPU enabled, or re-enable using only uint
			}

		  /*if(Counter100ms >= 100U) // Read pressure sensor only every 100ms
			{
				LPS22HH_Pressure_Task();
				Counter100ms = 0U;
			}
			if(Counter20ms >= 20U) // Read pressure sensor only every 20ms
			{
				LIS2MDL_Magnetom_Task();
				Counter20ms = 0U;
			}*/
		}

	}
}
